# Generated by Django 4.2.13 on 2026-04-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('onset_date', models.CharField(max_length=50)),
                ('resolution_date', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening')], max_length=20)),
                ('causality', models.CharField(choices=[('related', 'Related'), ('unrelated', 'Unrelated'), ('possible', 'Possible'), ('probable', 'Probable')], max_length=20)),
                ('event_description', models.TextField(blank=True)),
                ('action_taken', models.CharField(choices=[('none', 'None'), ('dose_reduced', 'Dose Reduced'), ('drug_stopped', 'Drug Stopped'), ('hospitalized', 'Hospitalized')], max_length=20)),
                ('outcome', models.CharField(choices=[('recovered', 'Recovered'), ('recovering', 'Recovering'), ('ongoing', 'Ongoing'), ('fatal', 'Fatal'), ('unknown', 'Unknown')], max_length=20)),
                ('is_sae', models.BooleanField(default=False)),
                ('sae_report_number', models.CharField(blank=True, max_length=50)),
                ('reported_by', models.CharField(max_length=100)),
                ('report_date', models.CharField(max_length=50)),
                ('regulatory_reported', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ae_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
