# Generated by Django 4.2.13 on 2026-04-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_collection_date', models.CharField(max_length=50)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('tissue', 'Tissue'), ('csf', 'CSF')], max_length=20)),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('reference_range_low', models.CharField(max_length=50)),
                ('reference_range_high', models.CharField(max_length=50)),
                ('abnormal_flag', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('lab_technician', models.CharField(max_length=100)),
                ('lab_name', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='visits.visitlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
