# Generated by Django 4.2.13 on 2026-04-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(max_length=20)),
                ('visit_date', models.CharField(max_length=50)),
                ('visit_type', models.CharField(choices=[('screening', 'Screening'), ('baseline', 'Baseline'), ('followup', 'Follow-up'), ('final', 'Final Visit'), ('unscheduled', 'Unscheduled')], max_length=20)),
                ('investigator_name', models.CharField(max_length=100)),
                ('systolic_bp', models.CharField(max_length=20)),
                ('diastolic_bp', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
                ('body_temperature', models.CharField(max_length=20)),
                ('oxygen_saturation', models.CharField(max_length=20)),
                ('visit_notes', models.TextField(blank=True)),
                ('next_visit_date', models.CharField(blank=True, max_length=50)),
                ('protocol_deviation', models.BooleanField(default=False)),
                ('deviation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
